/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OldToNewSecurityLevelMappingsBean from './OldToNewSecurityLevelMappingsBean';

/**
 * The AssociateSecuritySchemeWithProjectDetails model module.
 * @module model/AssociateSecuritySchemeWithProjectDetails
 * @version 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 */
class AssociateSecuritySchemeWithProjectDetails {
    /**
     * Constructs a new <code>AssociateSecuritySchemeWithProjectDetails</code>.
     * Issue security scheme, project, and remapping details.
     * @alias module:model/AssociateSecuritySchemeWithProjectDetails
     * @param projectId {String} The ID of the project.
     * @param schemeId {String} The ID of the issue security scheme. Providing null will clear the association with the issue security scheme.
     */
    constructor(projectId, schemeId) { 
        
        AssociateSecuritySchemeWithProjectDetails.initialize(this, projectId, schemeId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, projectId, schemeId) { 
        obj['projectId'] = projectId;
        obj['schemeId'] = schemeId;
    }

    /**
     * Constructs a <code>AssociateSecuritySchemeWithProjectDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssociateSecuritySchemeWithProjectDetails} obj Optional instance to populate.
     * @return {module:model/AssociateSecuritySchemeWithProjectDetails} The populated <code>AssociateSecuritySchemeWithProjectDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssociateSecuritySchemeWithProjectDetails();

            if (data.hasOwnProperty('oldToNewSecurityLevelMappings')) {
                obj['oldToNewSecurityLevelMappings'] = ApiClient.convertToType(data['oldToNewSecurityLevelMappings'], [OldToNewSecurityLevelMappingsBean]);
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'String');
            }
            if (data.hasOwnProperty('schemeId')) {
                obj['schemeId'] = ApiClient.convertToType(data['schemeId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssociateSecuritySchemeWithProjectDetails</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssociateSecuritySchemeWithProjectDetails</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AssociateSecuritySchemeWithProjectDetails.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['oldToNewSecurityLevelMappings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['oldToNewSecurityLevelMappings'])) {
                throw new Error("Expected the field `oldToNewSecurityLevelMappings` to be an array in the JSON data but got " + data['oldToNewSecurityLevelMappings']);
            }
            // validate the optional field `oldToNewSecurityLevelMappings` (array)
            for (const item of data['oldToNewSecurityLevelMappings']) {
                OldToNewSecurityLevelMappingsBean.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['projectId'] && !(typeof data['projectId'] === 'string' || data['projectId'] instanceof String)) {
            throw new Error("Expected the field `projectId` to be a primitive type in the JSON string but got " + data['projectId']);
        }
        // ensure the json data is a string
        if (data['schemeId'] && !(typeof data['schemeId'] === 'string' || data['schemeId'] instanceof String)) {
            throw new Error("Expected the field `schemeId` to be a primitive type in the JSON string but got " + data['schemeId']);
        }

        return true;
    }


}

AssociateSecuritySchemeWithProjectDetails.RequiredProperties = ["projectId", "schemeId"];

/**
 * The list of scheme levels which should be remapped to new levels of the issue security scheme.
 * @member {Array.<module:model/OldToNewSecurityLevelMappingsBean>} oldToNewSecurityLevelMappings
 */
AssociateSecuritySchemeWithProjectDetails.prototype['oldToNewSecurityLevelMappings'] = undefined;

/**
 * The ID of the project.
 * @member {String} projectId
 */
AssociateSecuritySchemeWithProjectDetails.prototype['projectId'] = undefined;

/**
 * The ID of the issue security scheme. Providing null will clear the association with the issue security scheme.
 * @member {String} schemeId
 */
AssociateSecuritySchemeWithProjectDetails.prototype['schemeId'] = undefined;






export default AssociateSecuritySchemeWithProjectDetails;

