/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BulkEditActionError from './BulkEditActionError';

/**
 * The BulkEditShareableEntityResponse model module.
 * @module model/BulkEditShareableEntityResponse
 * @version 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 */
class BulkEditShareableEntityResponse {
    /**
     * Constructs a new <code>BulkEditShareableEntityResponse</code>.
     * Details of a request to bulk edit shareable entity.
     * @alias module:model/BulkEditShareableEntityResponse
     * @param action {module:model/BulkEditShareableEntityResponse.ActionEnum} Allowed action for bulk edit shareable entity
     */
    constructor(action) { 
        
        BulkEditShareableEntityResponse.initialize(this, action);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action) { 
        obj['action'] = action;
    }

    /**
     * Constructs a <code>BulkEditShareableEntityResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BulkEditShareableEntityResponse} obj Optional instance to populate.
     * @return {module:model/BulkEditShareableEntityResponse} The populated <code>BulkEditShareableEntityResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BulkEditShareableEntityResponse();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('entityErrors')) {
                obj['entityErrors'] = ApiClient.convertToType(data['entityErrors'], {'String': BulkEditActionError});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BulkEditShareableEntityResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BulkEditShareableEntityResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BulkEditShareableEntityResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }

        return true;
    }


}

BulkEditShareableEntityResponse.RequiredProperties = ["action"];

/**
 * Allowed action for bulk edit shareable entity
 * @member {module:model/BulkEditShareableEntityResponse.ActionEnum} action
 */
BulkEditShareableEntityResponse.prototype['action'] = undefined;

/**
 * The mapping dashboard id to errors if any.
 * @member {Object.<String, module:model/BulkEditActionError>} entityErrors
 */
BulkEditShareableEntityResponse.prototype['entityErrors'] = undefined;





/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
BulkEditShareableEntityResponse['ActionEnum'] = {

    /**
     * value: "changeOwner"
     * @const
     */
    "changeOwner": "changeOwner",

    /**
     * value: "changePermission"
     * @const
     */
    "changePermission": "changePermission",

    /**
     * value: "addPermission"
     * @const
     */
    "addPermission": "addPermission",

    /**
     * value: "removePermission"
     * @const
     */
    "removePermission": "removePermission"
};



export default BulkEditShareableEntityResponse;

