/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateBoardRequestLocation model module.
 * @module model/CreateBoardRequestLocation
 * @version 1001.0.0
 */
class CreateBoardRequestLocation {
    /**
     * Constructs a new <code>CreateBoardRequestLocation</code>.
     * @alias module:model/CreateBoardRequestLocation
     */
    constructor() { 
        
        CreateBoardRequestLocation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateBoardRequestLocation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateBoardRequestLocation} obj Optional instance to populate.
     * @return {module:model/CreateBoardRequestLocation} The populated <code>CreateBoardRequestLocation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateBoardRequestLocation();

            if (data.hasOwnProperty('projectKeyOrId')) {
                obj['projectKeyOrId'] = ApiClient.convertToType(data['projectKeyOrId'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateBoardRequestLocation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateBoardRequestLocation</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['projectKeyOrId'] && !(typeof data['projectKeyOrId'] === 'string' || data['projectKeyOrId'] instanceof String)) {
            throw new Error("Expected the field `projectKeyOrId` to be a primitive type in the JSON string but got " + data['projectKeyOrId']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}



/**
 * @member {String} projectKeyOrId
 */
CreateBoardRequestLocation.prototype['projectKeyOrId'] = undefined;

/**
 * @member {module:model/CreateBoardRequestLocation.TypeEnum} type
 */
CreateBoardRequestLocation.prototype['type'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CreateBoardRequestLocation['TypeEnum'] = {

    /**
     * value: "project"
     * @const
     */
    "project": "project",

    /**
     * value: "user"
     * @const
     */
    "user": "user"
};



export default CreateBoardRequestLocation;

