/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateBoardRequestLocation from './CreateBoardRequestLocation';

/**
 * The CreateBoardRequest model module.
 * @module model/CreateBoardRequest
 * @version 1001.0.0
 */
class CreateBoardRequest {
    /**
     * Constructs a new <code>CreateBoardRequest</code>.
     * @alias module:model/CreateBoardRequest
     */
    constructor() { 
        
        CreateBoardRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateBoardRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateBoardRequest} obj Optional instance to populate.
     * @return {module:model/CreateBoardRequest} The populated <code>CreateBoardRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateBoardRequest();

            if (data.hasOwnProperty('filterId')) {
                obj['filterId'] = ApiClient.convertToType(data['filterId'], 'Number');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = CreateBoardRequestLocation.constructFromObject(data['location']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateBoardRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateBoardRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `location`
        if (data['location']) { // data not null
          CreateBoardRequestLocation.validateJSON(data['location']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}



/**
 * @member {Number} filterId
 */
CreateBoardRequest.prototype['filterId'] = undefined;

/**
 * @member {module:model/CreateBoardRequestLocation} location
 */
CreateBoardRequest.prototype['location'] = undefined;

/**
 * @member {String} name
 */
CreateBoardRequest.prototype['name'] = undefined;

/**
 * @member {module:model/CreateBoardRequest.TypeEnum} type
 */
CreateBoardRequest.prototype['type'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CreateBoardRequest['TypeEnum'] = {

    /**
     * value: "kanban"
     * @const
     */
    "kanban": "kanban",

    /**
     * value: "scrum"
     * @const
     */
    "scrum": "scrum",

    /**
     * value: "agility"
     * @const
     */
    "agility": "agility"
};



export default CreateBoardRequest;

