/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf model module.
 * @module model/DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf
 * @version 1001.0.0
 */
class DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf {
    /**
     * Constructs a new <code>DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf</code>.
     * Identifies an individual commit in a repository. 
     * @alias module:model/DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf
     * @param commitHash {String} The hash for the Commit. 
     * @param repositoryId {String} The ID of the Repository that the Commit belongs to. 
     */
    constructor(commitHash, repositoryId) { 
        
        DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf.initialize(this, commitHash, repositoryId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, commitHash, repositoryId) { 
        obj['commitHash'] = commitHash;
        obj['repositoryId'] = repositoryId;
    }

    /**
     * Constructs a <code>DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf} obj Optional instance to populate.
     * @return {module:model/DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf} The populated <code>DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf();

            if (data.hasOwnProperty('commitHash')) {
                obj['commitHash'] = ApiClient.convertToType(data['commitHash'], 'String');
            }
            if (data.hasOwnProperty('repositoryId')) {
                obj['repositoryId'] = ApiClient.convertToType(data['repositoryId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['commitHash'] && !(typeof data['commitHash'] === 'string' || data['commitHash'] instanceof String)) {
            throw new Error("Expected the field `commitHash` to be a primitive type in the JSON string but got " + data['commitHash']);
        }
        // ensure the json data is a string
        if (data['repositoryId'] && !(typeof data['repositoryId'] === 'string' || data['repositoryId'] instanceof String)) {
            throw new Error("Expected the field `repositoryId` to be a primitive type in the JSON string but got " + data['repositoryId']);
        }

        return true;
    }


}

DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf.RequiredProperties = ["commitHash", "repositoryId"];

/**
 * The hash for the Commit. 
 * @member {String} commitHash
 */
DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf.prototype['commitHash'] = undefined;

/**
 * The ID of the Repository that the Commit belongs to. 
 * @member {String} repositoryId
 */
DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf.prototype['repositoryId'] = undefined;






export default DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf;

