/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1 model module.
 * @module model/DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1
 * @version 1001.0.0
 */
class DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1 {
    /**
     * Constructs a new <code>DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1</code>.
     * Identifies an individual repository. 
     * @alias module:model/DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1
     * @param repositoryId {String} 
     */
    constructor(repositoryId) { 
        
        DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1.initialize(this, repositoryId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, repositoryId) { 
        obj['repositoryId'] = repositoryId;
    }

    /**
     * Constructs a <code>DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1} obj Optional instance to populate.
     * @return {module:model/DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1} The populated <code>DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1();

            if (data.hasOwnProperty('repositoryId')) {
                obj['repositoryId'] = ApiClient.convertToType(data['repositoryId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['repositoryId'] && !(typeof data['repositoryId'] === 'string' || data['repositoryId'] instanceof String)) {
            throw new Error("Expected the field `repositoryId` to be a primitive type in the JSON string but got " + data['repositoryId']);
        }

        return true;
    }


}

DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1.RequiredProperties = ["repositoryId"];

/**
 * 
 * @member {String} repositoryId
 */
DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1.prototype['repositoryId'] = undefined;






export default DeploymentDataAssociationsInnerAnyOf2ValuesInnerAnyOf1;

