/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeploymentDataAssociationsInnerAnyOf model module.
 * @module model/DeploymentDataAssociationsInnerAnyOf
 * @version 1001.0.0
 */
class DeploymentDataAssociationsInnerAnyOf {
    /**
     * Constructs a new <code>DeploymentDataAssociationsInnerAnyOf</code>.
     * An association type referencing issues in Jira. 
     * @alias module:model/DeploymentDataAssociationsInnerAnyOf
     * @param associationType {module:model/DeploymentDataAssociationsInnerAnyOf.AssociationTypeEnum} Defines the asssociation type. 
     * @param values {Array.<String>} The Jira issue keys to associate the Deployment information with.  The number of values counted across all associationTypes (issueKeys, issueIdOrKeys and serviceIdOrKeys) must not exceed a limit of 500. 
     */
    constructor(associationType, values) { 
        
        DeploymentDataAssociationsInnerAnyOf.initialize(this, associationType, values);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, associationType, values) { 
        obj['associationType'] = associationType;
        obj['values'] = values;
    }

    /**
     * Constructs a <code>DeploymentDataAssociationsInnerAnyOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeploymentDataAssociationsInnerAnyOf} obj Optional instance to populate.
     * @return {module:model/DeploymentDataAssociationsInnerAnyOf} The populated <code>DeploymentDataAssociationsInnerAnyOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeploymentDataAssociationsInnerAnyOf();

            if (data.hasOwnProperty('associationType')) {
                obj['associationType'] = ApiClient.convertToType(data['associationType'], 'String');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeploymentDataAssociationsInnerAnyOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeploymentDataAssociationsInnerAnyOf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeploymentDataAssociationsInnerAnyOf.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['associationType'] && !(typeof data['associationType'] === 'string' || data['associationType'] instanceof String)) {
            throw new Error("Expected the field `associationType` to be a primitive type in the JSON string but got " + data['associationType']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['values'])) {
            throw new Error("Expected the field `values` to be an array in the JSON data but got " + data['values']);
        }

        return true;
    }


}

DeploymentDataAssociationsInnerAnyOf.RequiredProperties = ["associationType", "values"];

/**
 * Defines the asssociation type. 
 * @member {module:model/DeploymentDataAssociationsInnerAnyOf.AssociationTypeEnum} associationType
 */
DeploymentDataAssociationsInnerAnyOf.prototype['associationType'] = undefined;

/**
 * The Jira issue keys to associate the Deployment information with.  The number of values counted across all associationTypes (issueKeys, issueIdOrKeys and serviceIdOrKeys) must not exceed a limit of 500. 
 * @member {Array.<String>} values
 */
DeploymentDataAssociationsInnerAnyOf.prototype['values'] = undefined;





/**
 * Allowed values for the <code>associationType</code> property.
 * @enum {String}
 * @readonly
 */
DeploymentDataAssociationsInnerAnyOf['AssociationTypeEnum'] = {

    /**
     * value: "issueKeys"
     * @const
     */
    "issueKeys": "issueKeys",

    /**
     * value: "issueIdOrKeys"
     * @const
     */
    "issueIdOrKeys": "issueIdOrKeys"
};



export default DeploymentDataAssociationsInnerAnyOf;

