/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorMessage from './ErrorMessage';

/**
 * The EntityError model module.
 * @module model/EntityError
 * @version 1001.0.0
 */
class EntityError {
    /**
     * Constructs a new <code>EntityError</code>.
     * Represents an error that happened with particular entity.
     * @alias module:model/EntityError
     * @param id {String} Entity id
     */
    constructor(id) { 
        
        EntityError.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>EntityError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityError} obj Optional instance to populate.
     * @return {module:model/EntityError} The populated <code>EntityError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityError();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('errorMessages')) {
                obj['errorMessages'] = ApiClient.convertToType(data['errorMessages'], [ErrorMessage]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EntityError</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EntityError</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EntityError.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        if (data['errorMessages']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['errorMessages'])) {
                throw new Error("Expected the field `errorMessages` to be an array in the JSON data but got " + data['errorMessages']);
            }
            // validate the optional field `errorMessages` (array)
            for (const item of data['errorMessages']) {
                ErrorMessage.validateJSON(item);
            };
        }

        return true;
    }


}

EntityError.RequiredProperties = ["id"];

/**
 * Entity id
 * @member {String} id
 */
EntityError.prototype['id'] = undefined;

/**
 * Error message
 * @member {Array.<module:model/ErrorMessage>} errorMessages
 */
EntityError.prototype['errorMessages'] = undefined;






export default EntityError;

