/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EpicRankRequestBean model module.
 * @module model/EpicRankRequestBean
 * @version 1001.0.0
 */
class EpicRankRequestBean {
    /**
     * Constructs a new <code>EpicRankRequestBean</code>.
     * @alias module:model/EpicRankRequestBean
     */
    constructor() { 
        
        EpicRankRequestBean.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EpicRankRequestBean</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EpicRankRequestBean} obj Optional instance to populate.
     * @return {module:model/EpicRankRequestBean} The populated <code>EpicRankRequestBean</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EpicRankRequestBean();

            if (data.hasOwnProperty('rankAfterEpic')) {
                obj['rankAfterEpic'] = ApiClient.convertToType(data['rankAfterEpic'], 'String');
            }
            if (data.hasOwnProperty('rankBeforeEpic')) {
                obj['rankBeforeEpic'] = ApiClient.convertToType(data['rankBeforeEpic'], 'String');
            }
            if (data.hasOwnProperty('rankCustomFieldId')) {
                obj['rankCustomFieldId'] = ApiClient.convertToType(data['rankCustomFieldId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EpicRankRequestBean</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EpicRankRequestBean</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['rankAfterEpic'] && !(typeof data['rankAfterEpic'] === 'string' || data['rankAfterEpic'] instanceof String)) {
            throw new Error("Expected the field `rankAfterEpic` to be a primitive type in the JSON string but got " + data['rankAfterEpic']);
        }
        // ensure the json data is a string
        if (data['rankBeforeEpic'] && !(typeof data['rankBeforeEpic'] === 'string' || data['rankBeforeEpic'] instanceof String)) {
            throw new Error("Expected the field `rankBeforeEpic` to be a primitive type in the JSON string but got " + data['rankBeforeEpic']);
        }

        return true;
    }


}



/**
 * @member {String} rankAfterEpic
 */
EpicRankRequestBean.prototype['rankAfterEpic'] = undefined;

/**
 * @member {String} rankBeforeEpic
 */
EpicRankRequestBean.prototype['rankBeforeEpic'] = undefined;

/**
 * @member {Number} rankCustomFieldId
 */
EpicRankRequestBean.prototype['rankCustomFieldId'] = undefined;






export default EpicRankRequestBean;

