/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FilterSubscriptionGroup from './FilterSubscriptionGroup';
import FilterSubscriptionUser from './FilterSubscriptionUser';

/**
 * The FilterSubscription model module.
 * @module model/FilterSubscription
 * @version 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 */
class FilterSubscription {
    /**
     * Constructs a new <code>FilterSubscription</code>.
     * Details of a user or group subscribing to a filter.
     * @alias module:model/FilterSubscription
     */
    constructor() { 
        
        FilterSubscription.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FilterSubscription</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FilterSubscription} obj Optional instance to populate.
     * @return {module:model/FilterSubscription} The populated <code>FilterSubscription</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FilterSubscription();

            if (data.hasOwnProperty('group')) {
                obj['group'] = FilterSubscriptionGroup.constructFromObject(data['group']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = FilterSubscriptionUser.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FilterSubscription</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FilterSubscription</code>.
     */
    static validateJSON(data) {
        // validate the optional field `group`
        if (data['group']) { // data not null
          FilterSubscriptionGroup.validateJSON(data['group']);
        }
        // validate the optional field `user`
        if (data['user']) { // data not null
          FilterSubscriptionUser.validateJSON(data['user']);
        }

        return true;
    }


}



/**
 * @member {module:model/FilterSubscriptionGroup} group
 */
FilterSubscription.prototype['group'] = undefined;

/**
 * The ID of the filter subscription.
 * @member {Number} id
 */
FilterSubscription.prototype['id'] = undefined;

/**
 * @member {module:model/FilterSubscriptionUser} user
 */
FilterSubscription.prototype['user'] = undefined;






export default FilterSubscription;

