/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner model module.
 * @module model/GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner
 * @version 1001.0.0
 */
class GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner {
    /**
     * Constructs a new <code>GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner</code>.
     * @alias module:model/GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner
     */
    constructor() { 
        
        GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner} obj Optional instance to populate.
     * @return {module:model/GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner} The populated <code>GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('self')) {
                obj['self'] = ApiClient.convertToType(data['self'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['self'] && !(typeof data['self'] === 'string' || data['self'] instanceof String)) {
            throw new Error("Expected the field `self` to be a primitive type in the JSON string but got " + data['self']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner.prototype['id'] = undefined;

/**
 * @member {String} self
 */
GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner.prototype['self'] = undefined;






export default GetConfiguration200ResponseColumnConfigColumnsInnerStatusesInner;

