/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdSearchRequestBean model module.
 * @module model/IdSearchRequestBean
 * @version 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 */
class IdSearchRequestBean {
    /**
     * Constructs a new <code>IdSearchRequestBean</code>.
     * @alias module:model/IdSearchRequestBean
     */
    constructor() { 
        
        IdSearchRequestBean.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdSearchRequestBean</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdSearchRequestBean} obj Optional instance to populate.
     * @return {module:model/IdSearchRequestBean} The populated <code>IdSearchRequestBean</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdSearchRequestBean();

            if (data.hasOwnProperty('jql')) {
                obj['jql'] = ApiClient.convertToType(data['jql'], 'String');
            }
            if (data.hasOwnProperty('maxResults')) {
                obj['maxResults'] = ApiClient.convertToType(data['maxResults'], 'Number');
            }
            if (data.hasOwnProperty('nextPageToken')) {
                obj['nextPageToken'] = ApiClient.convertToType(data['nextPageToken'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IdSearchRequestBean</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IdSearchRequestBean</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['jql'] && !(typeof data['jql'] === 'string' || data['jql'] instanceof String)) {
            throw new Error("Expected the field `jql` to be a primitive type in the JSON string but got " + data['jql']);
        }
        // ensure the json data is a string
        if (data['nextPageToken'] && !(typeof data['nextPageToken'] === 'string' || data['nextPageToken'] instanceof String)) {
            throw new Error("Expected the field `nextPageToken` to be a primitive type in the JSON string but got " + data['nextPageToken']);
        }

        return true;
    }


}



/**
 * A [JQL](https://confluence.atlassian.com/x/egORLQ) expression. Order by clauses are not allowed.
 * @member {String} jql
 */
IdSearchRequestBean.prototype['jql'] = undefined;

/**
 * The maximum number of items to return per page.
 * @member {Number} maxResults
 * @default 1000
 */
IdSearchRequestBean.prototype['maxResults'] = 1000;

/**
 * The continuation token to fetch the next page. This token is provided by the response of this endpoint.
 * @member {String} nextPageToken
 */
IdSearchRequestBean.prototype['nextPageToken'] = undefined;






export default IdSearchRequestBean;

