/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IssueBeanTransitionsInnerToAllOfScopeAllOfProject from './IssueBeanTransitionsInnerToAllOfScopeAllOfProject';

/**
 * The IssueBeanTransitionsInnerToAllOfScope model module.
 * @module model/IssueBeanTransitionsInnerToAllOfScope
 * @version 1001.0.0
 */
class IssueBeanTransitionsInnerToAllOfScope {
    /**
     * Constructs a new <code>IssueBeanTransitionsInnerToAllOfScope</code>.
     * The scope of the field.
     * @alias module:model/IssueBeanTransitionsInnerToAllOfScope
     */
    constructor() { 
        
        IssueBeanTransitionsInnerToAllOfScope.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IssueBeanTransitionsInnerToAllOfScope</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IssueBeanTransitionsInnerToAllOfScope} obj Optional instance to populate.
     * @return {module:model/IssueBeanTransitionsInnerToAllOfScope} The populated <code>IssueBeanTransitionsInnerToAllOfScope</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IssueBeanTransitionsInnerToAllOfScope();

            if (data.hasOwnProperty('project')) {
                obj['project'] = IssueBeanTransitionsInnerToAllOfScopeAllOfProject.constructFromObject(data['project']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IssueBeanTransitionsInnerToAllOfScope</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IssueBeanTransitionsInnerToAllOfScope</code>.
     */
    static validateJSON(data) {
        // validate the optional field `project`
        if (data['project']) { // data not null
          IssueBeanTransitionsInnerToAllOfScopeAllOfProject.validateJSON(data['project']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}



/**
 * @member {module:model/IssueBeanTransitionsInnerToAllOfScopeAllOfProject} project
 */
IssueBeanTransitionsInnerToAllOfScope.prototype['project'] = undefined;

/**
 * The type of scope.
 * @member {module:model/IssueBeanTransitionsInnerToAllOfScope.TypeEnum} type
 */
IssueBeanTransitionsInnerToAllOfScope.prototype['type'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
IssueBeanTransitionsInnerToAllOfScope['TypeEnum'] = {

    /**
     * value: "PROJECT"
     * @const
     */
    "PROJECT": "PROJECT",

    /**
     * value: "TEMPLATE"
     * @const
     */
    "TEMPLATE": "TEMPLATE"
};



export default IssueBeanTransitionsInnerToAllOfScope;

