/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IssueRankRequestBean model module.
 * @module model/IssueRankRequestBean
 * @version 1001.0.0
 */
class IssueRankRequestBean {
    /**
     * Constructs a new <code>IssueRankRequestBean</code>.
     * @alias module:model/IssueRankRequestBean
     */
    constructor() { 
        
        IssueRankRequestBean.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IssueRankRequestBean</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IssueRankRequestBean} obj Optional instance to populate.
     * @return {module:model/IssueRankRequestBean} The populated <code>IssueRankRequestBean</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IssueRankRequestBean();

            if (data.hasOwnProperty('issues')) {
                obj['issues'] = ApiClient.convertToType(data['issues'], ['String']);
            }
            if (data.hasOwnProperty('rankAfterIssue')) {
                obj['rankAfterIssue'] = ApiClient.convertToType(data['rankAfterIssue'], 'String');
            }
            if (data.hasOwnProperty('rankBeforeIssue')) {
                obj['rankBeforeIssue'] = ApiClient.convertToType(data['rankBeforeIssue'], 'String');
            }
            if (data.hasOwnProperty('rankCustomFieldId')) {
                obj['rankCustomFieldId'] = ApiClient.convertToType(data['rankCustomFieldId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IssueRankRequestBean</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IssueRankRequestBean</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['issues'])) {
            throw new Error("Expected the field `issues` to be an array in the JSON data but got " + data['issues']);
        }
        // ensure the json data is a string
        if (data['rankAfterIssue'] && !(typeof data['rankAfterIssue'] === 'string' || data['rankAfterIssue'] instanceof String)) {
            throw new Error("Expected the field `rankAfterIssue` to be a primitive type in the JSON string but got " + data['rankAfterIssue']);
        }
        // ensure the json data is a string
        if (data['rankBeforeIssue'] && !(typeof data['rankBeforeIssue'] === 'string' || data['rankBeforeIssue'] instanceof String)) {
            throw new Error("Expected the field `rankBeforeIssue` to be a primitive type in the JSON string but got " + data['rankBeforeIssue']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} issues
 */
IssueRankRequestBean.prototype['issues'] = undefined;

/**
 * @member {String} rankAfterIssue
 */
IssueRankRequestBean.prototype['rankAfterIssue'] = undefined;

/**
 * @member {String} rankBeforeIssue
 */
IssueRankRequestBean.prototype['rankBeforeIssue'] = undefined;

/**
 * @member {Number} rankCustomFieldId
 */
IssueRankRequestBean.prototype['rankCustomFieldId'] = undefined;






export default IssueRankRequestBean;

