/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JiraSelectedOptionField from './JiraSelectedOptionField';

/**
 * The JiraSingleSelectField model module.
 * @module model/JiraSingleSelectField
 * @version 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 */
class JiraSingleSelectField {
    /**
     * Constructs a new <code>JiraSingleSelectField</code>.
     * Add or clear a single select field:   *  To add, specify the option with an &#x60;optionId&#x60;.  *  To clear, pass an option with &#x60;optionId&#x60; as &#x60;-1&#x60;.
     * @alias module:model/JiraSingleSelectField
     * @param fieldId {String} 
     * @param option {module:model/JiraSelectedOptionField} 
     */
    constructor(fieldId, option) { 
        
        JiraSingleSelectField.initialize(this, fieldId, option);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fieldId, option) { 
        obj['fieldId'] = fieldId;
        obj['option'] = option;
    }

    /**
     * Constructs a <code>JiraSingleSelectField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JiraSingleSelectField} obj Optional instance to populate.
     * @return {module:model/JiraSingleSelectField} The populated <code>JiraSingleSelectField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JiraSingleSelectField();

            if (data.hasOwnProperty('fieldId')) {
                obj['fieldId'] = ApiClient.convertToType(data['fieldId'], 'String');
            }
            if (data.hasOwnProperty('option')) {
                obj['option'] = JiraSelectedOptionField.constructFromObject(data['option']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JiraSingleSelectField</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JiraSingleSelectField</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of JiraSingleSelectField.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['fieldId'] && !(typeof data['fieldId'] === 'string' || data['fieldId'] instanceof String)) {
            throw new Error("Expected the field `fieldId` to be a primitive type in the JSON string but got " + data['fieldId']);
        }
        // validate the optional field `option`
        if (data['option']) { // data not null
          JiraSelectedOptionField.validateJSON(data['option']);
        }

        return true;
    }


}

JiraSingleSelectField.RequiredProperties = ["fieldId", "option"];

/**
 * @member {String} fieldId
 */
JiraSingleSelectField.prototype['fieldId'] = undefined;

/**
 * @member {module:model/JiraSelectedOptionField} option
 */
JiraSingleSelectField.prototype['option'] = undefined;






export default JiraSingleSelectField;

