/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JiraDateTimeInput from './JiraDateTimeInput';

/**
 * The JiraDateTimeField model module.
 * @module model/JiraDateTimeField
 * @version 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 */
class JiraDateTimeField {
    /**
     * Constructs a new <code>JiraDateTimeField</code>.
     * @alias module:model/JiraDateTimeField
     * @param dateTime {module:model/JiraDateTimeInput} 
     * @param fieldId {String} 
     */
    constructor(dateTime, fieldId) { 
        
        JiraDateTimeField.initialize(this, dateTime, fieldId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, dateTime, fieldId) { 
        obj['dateTime'] = dateTime;
        obj['fieldId'] = fieldId;
    }

    /**
     * Constructs a <code>JiraDateTimeField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JiraDateTimeField} obj Optional instance to populate.
     * @return {module:model/JiraDateTimeField} The populated <code>JiraDateTimeField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JiraDateTimeField();

            if (data.hasOwnProperty('dateTime')) {
                obj['dateTime'] = JiraDateTimeInput.constructFromObject(data['dateTime']);
            }
            if (data.hasOwnProperty('fieldId')) {
                obj['fieldId'] = ApiClient.convertToType(data['fieldId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JiraDateTimeField</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JiraDateTimeField</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of JiraDateTimeField.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `dateTime`
        if (data['dateTime']) { // data not null
          JiraDateTimeInput.validateJSON(data['dateTime']);
        }
        // ensure the json data is a string
        if (data['fieldId'] && !(typeof data['fieldId'] === 'string' || data['fieldId'] instanceof String)) {
            throw new Error("Expected the field `fieldId` to be a primitive type in the JSON string but got " + data['fieldId']);
        }

        return true;
    }


}

JiraDateTimeField.RequiredProperties = ["dateTime", "fieldId"];

/**
 * @member {module:model/JiraDateTimeInput} dateTime
 */
JiraDateTimeField.prototype['dateTime'] = undefined;

/**
 * @member {String} fieldId
 */
JiraDateTimeField.prototype['fieldId'] = undefined;






export default JiraDateTimeField;

