/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JiraPriorityField model module.
 * @module model/JiraPriorityField
 * @version 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 */
class JiraPriorityField {
    /**
     * Constructs a new <code>JiraPriorityField</code>.
     * @alias module:model/JiraPriorityField
     * @param priorityId {String} 
     */
    constructor(priorityId) { 
        
        JiraPriorityField.initialize(this, priorityId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, priorityId) { 
        obj['priorityId'] = priorityId;
    }

    /**
     * Constructs a <code>JiraPriorityField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JiraPriorityField} obj Optional instance to populate.
     * @return {module:model/JiraPriorityField} The populated <code>JiraPriorityField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JiraPriorityField();

            if (data.hasOwnProperty('priorityId')) {
                obj['priorityId'] = ApiClient.convertToType(data['priorityId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JiraPriorityField</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JiraPriorityField</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of JiraPriorityField.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['priorityId'] && !(typeof data['priorityId'] === 'string' || data['priorityId'] instanceof String)) {
            throw new Error("Expected the field `priorityId` to be a primitive type in the JSON string but got " + data['priorityId']);
        }

        return true;
    }


}

JiraPriorityField.RequiredProperties = ["priorityId"];

/**
 * @member {String} priorityId
 */
JiraPriorityField.prototype['priorityId'] = undefined;






export default JiraPriorityField;

