/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JiraSelectedOptionField from './JiraSelectedOptionField';

/**
 * The JiraMultipleSelectField model module.
 * @module model/JiraMultipleSelectField
 * @version 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 */
class JiraMultipleSelectField {
    /**
     * Constructs a new <code>JiraMultipleSelectField</code>.
     * @alias module:model/JiraMultipleSelectField
     * @param fieldId {String} 
     * @param options {Array.<module:model/JiraSelectedOptionField>} 
     */
    constructor(fieldId, options) { 
        
        JiraMultipleSelectField.initialize(this, fieldId, options);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fieldId, options) { 
        obj['fieldId'] = fieldId;
        obj['options'] = options;
    }

    /**
     * Constructs a <code>JiraMultipleSelectField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JiraMultipleSelectField} obj Optional instance to populate.
     * @return {module:model/JiraMultipleSelectField} The populated <code>JiraMultipleSelectField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JiraMultipleSelectField();

            if (data.hasOwnProperty('fieldId')) {
                obj['fieldId'] = ApiClient.convertToType(data['fieldId'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], [JiraSelectedOptionField]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JiraMultipleSelectField</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JiraMultipleSelectField</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of JiraMultipleSelectField.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['fieldId'] && !(typeof data['fieldId'] === 'string' || data['fieldId'] instanceof String)) {
            throw new Error("Expected the field `fieldId` to be a primitive type in the JSON string but got " + data['fieldId']);
        }
        if (data['options']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['options'])) {
                throw new Error("Expected the field `options` to be an array in the JSON data but got " + data['options']);
            }
            // validate the optional field `options` (array)
            for (const item of data['options']) {
                JiraSelectedOptionField.validateJSON(item);
            };
        }

        return true;
    }


}

JiraMultipleSelectField.RequiredProperties = ["fieldId", "options"];

/**
 * @member {String} fieldId
 */
JiraMultipleSelectField.prototype['fieldId'] = undefined;

/**
 * @member {Array.<module:model/JiraSelectedOptionField>} options
 */
JiraMultipleSelectField.prototype['options'] = undefined;






export default JiraMultipleSelectField;

