/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PriorityWithSequence model module.
 * @module model/PriorityWithSequence
 * @version 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 */
class PriorityWithSequence {
    /**
     * Constructs a new <code>PriorityWithSequence</code>.
     * An issue priority with sequence information.
     * @alias module:model/PriorityWithSequence
     */
    constructor() { 
        
        PriorityWithSequence.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PriorityWithSequence</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PriorityWithSequence} obj Optional instance to populate.
     * @return {module:model/PriorityWithSequence} The populated <code>PriorityWithSequence</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PriorityWithSequence();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('iconUrl')) {
                obj['iconUrl'] = ApiClient.convertToType(data['iconUrl'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('isDefault')) {
                obj['isDefault'] = ApiClient.convertToType(data['isDefault'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('self')) {
                obj['self'] = ApiClient.convertToType(data['self'], 'String');
            }
            if (data.hasOwnProperty('sequence')) {
                obj['sequence'] = ApiClient.convertToType(data['sequence'], 'String');
            }
            if (data.hasOwnProperty('statusColor')) {
                obj['statusColor'] = ApiClient.convertToType(data['statusColor'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PriorityWithSequence</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PriorityWithSequence</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['iconUrl'] && !(typeof data['iconUrl'] === 'string' || data['iconUrl'] instanceof String)) {
            throw new Error("Expected the field `iconUrl` to be a primitive type in the JSON string but got " + data['iconUrl']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['self'] && !(typeof data['self'] === 'string' || data['self'] instanceof String)) {
            throw new Error("Expected the field `self` to be a primitive type in the JSON string but got " + data['self']);
        }
        // ensure the json data is a string
        if (data['sequence'] && !(typeof data['sequence'] === 'string' || data['sequence'] instanceof String)) {
            throw new Error("Expected the field `sequence` to be a primitive type in the JSON string but got " + data['sequence']);
        }
        // ensure the json data is a string
        if (data['statusColor'] && !(typeof data['statusColor'] === 'string' || data['statusColor'] instanceof String)) {
            throw new Error("Expected the field `statusColor` to be a primitive type in the JSON string but got " + data['statusColor']);
        }

        return true;
    }


}



/**
 * The description of the issue priority.
 * @member {String} description
 */
PriorityWithSequence.prototype['description'] = undefined;

/**
 * The URL of the icon for the issue priority.
 * @member {String} iconUrl
 */
PriorityWithSequence.prototype['iconUrl'] = undefined;

/**
 * The ID of the issue priority.
 * @member {String} id
 */
PriorityWithSequence.prototype['id'] = undefined;

/**
 * Whether this priority is the default.
 * @member {Boolean} isDefault
 */
PriorityWithSequence.prototype['isDefault'] = undefined;

/**
 * The name of the issue priority.
 * @member {String} name
 */
PriorityWithSequence.prototype['name'] = undefined;

/**
 * The URL of the issue priority.
 * @member {String} self
 */
PriorityWithSequence.prototype['self'] = undefined;

/**
 * The sequence of the issue priority.
 * @member {String} sequence
 */
PriorityWithSequence.prototype['sequence'] = undefined;

/**
 * The color used to indicate the issue priority.
 * @member {String} statusColor
 */
PriorityWithSequence.prototype['statusColor'] = undefined;






export default PriorityWithSequence;

