/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProjectAndIssueTypePair model module.
 * @module model/ProjectAndIssueTypePair
 * @version 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 */
class ProjectAndIssueTypePair {
    /**
     * Constructs a new <code>ProjectAndIssueTypePair</code>.
     * A project and issueType ID pair that identifies a status mapping.
     * @alias module:model/ProjectAndIssueTypePair
     * @param issueTypeId {String} The ID of the issue type.
     * @param projectId {String} The ID of the project.
     */
    constructor(issueTypeId, projectId) { 
        
        ProjectAndIssueTypePair.initialize(this, issueTypeId, projectId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, issueTypeId, projectId) { 
        obj['issueTypeId'] = issueTypeId;
        obj['projectId'] = projectId;
    }

    /**
     * Constructs a <code>ProjectAndIssueTypePair</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProjectAndIssueTypePair} obj Optional instance to populate.
     * @return {module:model/ProjectAndIssueTypePair} The populated <code>ProjectAndIssueTypePair</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectAndIssueTypePair();

            if (data.hasOwnProperty('issueTypeId')) {
                obj['issueTypeId'] = ApiClient.convertToType(data['issueTypeId'], 'String');
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProjectAndIssueTypePair</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProjectAndIssueTypePair</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProjectAndIssueTypePair.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['issueTypeId'] && !(typeof data['issueTypeId'] === 'string' || data['issueTypeId'] instanceof String)) {
            throw new Error("Expected the field `issueTypeId` to be a primitive type in the JSON string but got " + data['issueTypeId']);
        }
        // ensure the json data is a string
        if (data['projectId'] && !(typeof data['projectId'] === 'string' || data['projectId'] instanceof String)) {
            throw new Error("Expected the field `projectId` to be a primitive type in the JSON string but got " + data['projectId']);
        }

        return true;
    }


}

ProjectAndIssueTypePair.RequiredProperties = ["issueTypeId", "projectId"];

/**
 * The ID of the issue type.
 * @member {String} issueTypeId
 */
ProjectAndIssueTypePair.prototype['issueTypeId'] = undefined;

/**
 * The ID of the project.
 * @member {String} projectId
 */
ProjectAndIssueTypePair.prototype['projectId'] = undefined;






export default ProjectAndIssueTypePair;

