/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BuildKey from './BuildKey';
import ErrorMessage from './ErrorMessage';

/**
 * The RejectedBuild model module.
 * @module model/RejectedBuild
 * @version 1001.0.0
 */
class RejectedBuild {
    /**
     * Constructs a new <code>RejectedBuild</code>.
     * A build that has not been accepted for submission, usually due to a problem with the request data.  The object is comprised of the key of the rejected build and the corresponding error messages. 
     * @alias module:model/RejectedBuild
     * @param key {module:model/BuildKey} 
     * @param errors {Array.<module:model/ErrorMessage>} The error messages for the rejected build
     */
    constructor(key, errors) { 
        
        RejectedBuild.initialize(this, key, errors);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key, errors) { 
        obj['key'] = key;
        obj['errors'] = errors;
    }

    /**
     * Constructs a <code>RejectedBuild</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RejectedBuild} obj Optional instance to populate.
     * @return {module:model/RejectedBuild} The populated <code>RejectedBuild</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RejectedBuild();

            if (data.hasOwnProperty('key')) {
                obj['key'] = BuildKey.constructFromObject(data['key']);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [ErrorMessage]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RejectedBuild</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RejectedBuild</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RejectedBuild.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `key`
        if (data['key']) { // data not null
          BuildKey.validateJSON(data['key']);
        }
        if (data['errors']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['errors'])) {
                throw new Error("Expected the field `errors` to be an array in the JSON data but got " + data['errors']);
            }
            // validate the optional field `errors` (array)
            for (const item of data['errors']) {
                ErrorMessage.validateJSON(item);
            };
        }

        return true;
    }


}

RejectedBuild.RequiredProperties = ["key", "errors"];

/**
 * @member {module:model/BuildKey} key
 */
RejectedBuild.prototype['key'] = undefined;

/**
 * The error messages for the rejected build
 * @member {Array.<module:model/ErrorMessage>} errors
 */
RejectedBuild.prototype['errors'] = undefined;






export default RejectedBuild;

