/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StoreDevinfoResultAcceptedDevinfoEntitiesValue model module.
 * @module model/StoreDevinfoResultAcceptedDevinfoEntitiesValue
 * @version 1001.0.0
 */
class StoreDevinfoResultAcceptedDevinfoEntitiesValue {
    /**
     * Constructs a new <code>StoreDevinfoResultAcceptedDevinfoEntitiesValue</code>.
     * IDs of entities grouped by entity type
     * @alias module:model/StoreDevinfoResultAcceptedDevinfoEntitiesValue
     */
    constructor() { 
        
        StoreDevinfoResultAcceptedDevinfoEntitiesValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StoreDevinfoResultAcceptedDevinfoEntitiesValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StoreDevinfoResultAcceptedDevinfoEntitiesValue} obj Optional instance to populate.
     * @return {module:model/StoreDevinfoResultAcceptedDevinfoEntitiesValue} The populated <code>StoreDevinfoResultAcceptedDevinfoEntitiesValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoreDevinfoResultAcceptedDevinfoEntitiesValue();

            if (data.hasOwnProperty('commits')) {
                obj['commits'] = ApiClient.convertToType(data['commits'], ['String']);
            }
            if (data.hasOwnProperty('branches')) {
                obj['branches'] = ApiClient.convertToType(data['branches'], ['String']);
            }
            if (data.hasOwnProperty('pullRequests')) {
                obj['pullRequests'] = ApiClient.convertToType(data['pullRequests'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StoreDevinfoResultAcceptedDevinfoEntitiesValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StoreDevinfoResultAcceptedDevinfoEntitiesValue</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['commits'])) {
            throw new Error("Expected the field `commits` to be an array in the JSON data but got " + data['commits']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['branches'])) {
            throw new Error("Expected the field `branches` to be an array in the JSON data but got " + data['branches']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['pullRequests'])) {
            throw new Error("Expected the field `pullRequests` to be an array in the JSON data but got " + data['pullRequests']);
        }

        return true;
    }


}



/**
 * Commits IDs
 * @member {Array.<String>} commits
 */
StoreDevinfoResultAcceptedDevinfoEntitiesValue.prototype['commits'] = undefined;

/**
 * Branch IDs
 * @member {Array.<String>} branches
 */
StoreDevinfoResultAcceptedDevinfoEntitiesValue.prototype['branches'] = undefined;

/**
 * Pull request IDs
 * @member {Array.<String>} pullRequests
 */
StoreDevinfoResultAcceptedDevinfoEntitiesValue.prototype['pullRequests'] = undefined;






export default StoreDevinfoResultAcceptedDevinfoEntitiesValue;

