/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorMessage1 from './ErrorMessage1';

/**
 * The SubmitIncidentsResponse model module.
 * @module model/SubmitIncidentsResponse
 * @version 1001.0.0
 */
class SubmitIncidentsResponse {
    /**
     * Constructs a new <code>SubmitIncidentsResponse</code>.
     * The result of a successful submitIncidents request. 
     * @alias module:model/SubmitIncidentsResponse
     */
    constructor() { 
        
        SubmitIncidentsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubmitIncidentsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubmitIncidentsResponse} obj Optional instance to populate.
     * @return {module:model/SubmitIncidentsResponse} The populated <code>SubmitIncidentsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubmitIncidentsResponse();

            if (data.hasOwnProperty('acceptedIncidents')) {
                obj['acceptedIncidents'] = ApiClient.convertToType(data['acceptedIncidents'], ['String']);
            }
            if (data.hasOwnProperty('failedIncidents')) {
                obj['failedIncidents'] = ApiClient.convertToType(data['failedIncidents'], {'String': [ErrorMessage1]});
            }
            if (data.hasOwnProperty('unknownProjectKeys')) {
                obj['unknownProjectKeys'] = ApiClient.convertToType(data['unknownProjectKeys'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubmitIncidentsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubmitIncidentsResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['acceptedIncidents'])) {
            throw new Error("Expected the field `acceptedIncidents` to be an array in the JSON data but got " + data['acceptedIncidents']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['unknownProjectKeys'])) {
            throw new Error("Expected the field `unknownProjectKeys` to be an array in the JSON data but got " + data['unknownProjectKeys']);
        }

        return true;
    }


}



/**
 * The IDs of Incidents that have been accepted for submission.  A Incident may be rejected if it was only associated with unknown project keys.  Note that a Incident that isn't updated due to it's updateSequenceNumber being out of order is not considered a failed submission. 
 * @member {Array.<String>} acceptedIncidents
 */
SubmitIncidentsResponse.prototype['acceptedIncidents'] = undefined;

/**
 * Details of Incidents that have not been accepted for submission, usually due to a problem with the request data.  The object (if present) will be keyed by Incident ID and include any errors associated with that Incident that have prevented it being submitted. 
 * @member {Object.<String, Array.<module:model/ErrorMessage1>>} failedIncidents
 */
SubmitIncidentsResponse.prototype['failedIncidents'] = undefined;

/**
 * Project keys that are not known on this Jira instance (if any).  These may be invalid keys (e.g. `UTF` is sometimes incorrectly identified as a Jira project key), or they may be for projects that no longer exist.  If a Incident has been associated with project keys other than those in this array it will still be stored against those valid keys. If a Incident was only associated with project keys deemed to be invalid it won't be persisted. 
 * @member {Array.<String>} unknownProjectKeys
 */
SubmitIncidentsResponse.prototype['unknownProjectKeys'] = undefined;






export default SubmitIncidentsResponse;

