/**
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Incident from './Incident';
import ProviderMetadata6 from './ProviderMetadata6';
import Review from './Review';
import SubmitIncidentsRequestAnyOf from './SubmitIncidentsRequestAnyOf';
import SubmitIncidentsRequestAnyOf1 from './SubmitIncidentsRequestAnyOf1';
// TODO: add anyof model support
