/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TargetStatus model module.
 * @module model/TargetStatus
 * @version 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 */
class TargetStatus {
    /**
     * Constructs a new <code>TargetStatus</code>.
     * Status mapping for statuses in source workflow to respective target status in target workflow.
     * @alias module:model/TargetStatus
     * @param statuses {Object.<String, Array.<String>>} An object with the key as the ID of the target status and value with the list of the IDs of the current source statuses.
     */
    constructor(statuses) { 
        
        TargetStatus.initialize(this, statuses);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, statuses) { 
        obj['statuses'] = statuses;
    }

    /**
     * Constructs a <code>TargetStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TargetStatus} obj Optional instance to populate.
     * @return {module:model/TargetStatus} The populated <code>TargetStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TargetStatus();

            if (data.hasOwnProperty('statuses')) {
                obj['statuses'] = ApiClient.convertToType(data['statuses'], {'String': ['String']});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TargetStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TargetStatus</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TargetStatus.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

TargetStatus.RequiredProperties = ["statuses"];

/**
 * An object with the key as the ID of the target status and value with the list of the IDs of the current source statuses.
 * @member {Object.<String, Array.<String>>} statuses
 */
TargetStatus.prototype['statuses'] = undefined;






export default TargetStatus;

