/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkflowValidationError from './WorkflowValidationError';

/**
 * The WorkflowValidationErrorList model module.
 * @module model/WorkflowValidationErrorList
 * @version 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 */
class WorkflowValidationErrorList {
    /**
     * Constructs a new <code>WorkflowValidationErrorList</code>.
     * @alias module:model/WorkflowValidationErrorList
     */
    constructor() { 
        
        WorkflowValidationErrorList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkflowValidationErrorList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowValidationErrorList} obj Optional instance to populate.
     * @return {module:model/WorkflowValidationErrorList} The populated <code>WorkflowValidationErrorList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowValidationErrorList();

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [WorkflowValidationError]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkflowValidationErrorList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkflowValidationErrorList</code>.
     */
    static validateJSON(data) {
        if (data['errors']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['errors'])) {
                throw new Error("Expected the field `errors` to be an array in the JSON data but got " + data['errors']);
            }
            // validate the optional field `errors` (array)
            for (const item of data['errors']) {
                WorkflowValidationError.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * The list of validation errors.
 * @member {Array.<module:model/WorkflowValidationError>} errors
 */
WorkflowValidationErrorList.prototype['errors'] = undefined;






export default WorkflowValidationErrorList;

