/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WorkflowTrigger model module.
 * @module model/WorkflowTrigger
 * @version 1001.0.0-SNAPSHOT-122db9bd6b089919e6465ce52fdce319d5a9dfb4
 */
class WorkflowTrigger {
    /**
     * Constructs a new <code>WorkflowTrigger</code>.
     * The trigger configuration associated with a workflow.
     * @alias module:model/WorkflowTrigger
     * @param parameters {Object.<String, String>} The parameters of the trigger.
     * @param ruleKey {String} The rule key of the trigger.
     */
    constructor(parameters, ruleKey) { 
        
        WorkflowTrigger.initialize(this, parameters, ruleKey);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, parameters, ruleKey) { 
        obj['parameters'] = parameters;
        obj['ruleKey'] = ruleKey;
    }

    /**
     * Constructs a <code>WorkflowTrigger</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowTrigger} obj Optional instance to populate.
     * @return {module:model/WorkflowTrigger} The populated <code>WorkflowTrigger</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowTrigger();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], {'String': 'String'});
            }
            if (data.hasOwnProperty('ruleKey')) {
                obj['ruleKey'] = ApiClient.convertToType(data['ruleKey'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkflowTrigger</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkflowTrigger</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WorkflowTrigger.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['ruleKey'] && !(typeof data['ruleKey'] === 'string' || data['ruleKey'] instanceof String)) {
            throw new Error("Expected the field `ruleKey` to be a primitive type in the JSON string but got " + data['ruleKey']);
        }

        return true;
    }


}

WorkflowTrigger.RequiredProperties = ["parameters", "ruleKey"];

/**
 * The ID of the trigger.
 * @member {String} id
 */
WorkflowTrigger.prototype['id'] = undefined;

/**
 * The parameters of the trigger.
 * @member {Object.<String, String>} parameters
 */
WorkflowTrigger.prototype['parameters'] = undefined;

/**
 * The rule key of the trigger.
 * @member {String} ruleKey
 */
WorkflowTrigger.prototype['ruleKey'] = undefined;






export default WorkflowTrigger;

